spring.application.name=backed

# server
server.port=${PORT:8080}

# H2 console (dev)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 in-memory datasource (dev)
spring.datasource.url=jdbc:h2:mem:railxpressdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# local file upload directory
file.upload-dir=uploads

# CORS
spring.mvc.cors.allowed-origins=http://localhost:5173

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahaktuwani8@gmail.com
spring.mail.password=wexpyazawpnzoqjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.from=mahaktuwani8@gmail.com
